<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>{{ $exportTitle }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 11px; color: #1e293b; padding: 24px; }
        .header { border-bottom: 2px solid #D56B8D; padding-bottom: 12px; margin-bottom: 16px; }
        .header h1 { font-size: 16px; color: #a23f66; margin-bottom: 4px; }
        .header .meta { font-size: 9px; color: #64748b; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { background-color: #fdf2f5; color: #a23f66; font-weight: 600; text-align: left; padding: 8px 10px; border-bottom: 2px solid #eedde2; font-size: 10px; text-transform: uppercase; }
        td { padding: 7px 10px; border-bottom: 1px solid #f1e4e8; font-size: 10px; }
        tr:nth-child(even) td { background-color: #fdf8fa; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #eedde2; font-size: 8px; color: #94a3b8; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $exportTitle }}</h1>
        <div class="meta">Generated: {{ $exportDate }} · Nailby Hilda</div>
        @if (!empty($filterDesc))
            <div class="meta" style="margin-top:2px;">Filters: {{ $filterDesc }}</div>
        @endif
    </div>

    <table>
        @if (!empty($columns))
        <thead>
            <tr>
                @foreach ($columns as $col)
                    <th>{{ $col }}</th>
                @endforeach
            </tr>
        </thead>
        @endif
        <tbody>
            @foreach ($rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td>{!! e($cell) !!}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Nailby Hilda — {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
